---
title: "Statistical testing of quantitative omics data"
author: "Veit Schwämmle"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Welcome to the vignette of the PolySTest package. We will run statistical tests for differential abundances in a proteomics data set. 


```{r, include=FALSE}
  # package raw data file
  filename <- system.file("extdata", "LiverAllProteins.csv", package = "PolySTest")
  NumReps <- 3
  NumCond <- 4
  isPaired <- TRUE

  ## Read file
  dat <- read.csv(filename, row.names=1, stringsAsFactors = F)

  ## Reduce to first 200
  dat <- dat[1:200,]

  sampleMetadata <- data.frame(Condition = rep(paste("Condition", 1:NumCond), NumReps),
                               Replicate = rep(1:NumReps, each=NumCond))

  # Create the SummarizedExperiment object
  fulldata <- SummarizedExperiment(assays = list(quant = dat),
                                   colData = sampleMetadata)
  # Adding metadata
  metadata(fulldata) <- list(
    NumReps = NumReps,
    NumCond = NumCond
  )

  # Access the assay data
  dat <- assay(fulldata, "quant")

  # Normalize
  dat <- t(t(dat) -
             colMedians(as.matrix(dat), na.rm = TRUE))

  # Update the assay data in 'fulldata'
  assay(fulldata, "quant") <- dat

  ####### Defining conditions from names
  fulldata <- update_conditions_with_lcs(fulldata)
  conditions <- unique(colData(fulldata)$Condition)

  ####### Defining comparison for statistical tests
  FullReg <- allComps <- NULL

  allComps <- create_pairwise_comparisons(conditions, 2)

  # Run paired tests
  fulldata <- PolySTest_paired(fulldata, allComps)

  DRFs <- rowData(fulldata)[,"FDR_PolySTest_HF.Rep._vs_TTA.Rep."] < 0.01
  expect_equal(sum(DRFs), 21)
  expect_match(rownames(rowData(fulldata))[4], "A7VJC2")

  # Run unpaired tests
  fulldata <- PolySTest_unpaired(fulldata, allComps)
  DRFs <- rowData(fulldata)[,"FDR_PolySTest_HF.Rep._vs_TTA.Rep."] < 0.01
  expect_equal(sum(DRFs), 21)
  expect_match(rownames(rowData(fulldata))[4], "A7VJC2")

```
